### ISSUE TITLE
max_length Bug?

### ISSUE THREAD

**Issue by maxbundscherer** [stefan-it/german-gpt2#2]
Hey,

thanks for the great work!

Unfortunately the ``config={'max_length':800})`` param dont works: "Input length of input_ids is 58, but ``max_length`` is set to 50."

I had tried a lot of combinations for the config param.

___

pipe = pipeline('text-generation', model="dbmdz/german-gpt2",
                 tokenizer="dbmdz/german-gpt2", **config={'max_length':800})**

**Comment by stefan-it** [comment]
Hi @maxbundscherer ,

thanks for your interest :hugs: 

Could you try using a more recent version of Transformers? I checked it with the current version (*4.2.1*) and text generation is working:

![image](https://user-images.githubusercontent.com/20651387/104855058-c7b4ec00-590a-11eb-8983-1dada25242ae.png)

**Comment by hackenjoe** [comment]
I have got the same issue. Seems to happen, when executing in JuypterLab.

**Comment by stefan-it** [comment]
Hi @hackenjoe ,

that's very interesting, I just installed latest version of JupyterLab:

![image](https://user-images.githubusercontent.com/20651387/104964762-6447be80-59dd-11eb-8b29-a014847141e7.png)

Could you specify your used Python version :thinking:

**Comment by maxbundscherer** [comment]
@stefan-it - Many thanks! Hero of the day! :)
