### ISSUE TITLE
Clarification question about tokenization/vocab

### ISSUE THREAD

**Issue by wbwseeker** [stefan-it/german-gpt2#3]
Hey,

first off thanks a lot for putting this model up on huggingface. It's really cool to see such big models arriving for other languages than English 👍 

I am trying to fine-tune the model on rather short texts and I was playing with special tokens to mark parts of the texts. While doing that I was looking at the tokenizer and the vocabulary and I saw that the vocab contains a few entries that look like they were used as special characters for bos/eos/pad/...

```
{
  "<s>": 0,
  "<pad>": 1,
  "</s>": 2,
  "<unk>": 3,
  "<mask>": 4,
  ...
```

Those are however not set when loading the tokenizer from the pretrained model but instead I get the default ones (which are not part of the vocab):
```
tokenizer = AutoTokenizer.from_pretrained("dbmdz/german-gpt2")
print(tokenizer.special_tokens_map)
```
gives

`{'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}`

When I look at the tokenizer_config.json, it doesn't say anything about special tokens. The model config contains the following lines:
```
{
...
"bos_token_id": 50256,
"eos_token_id": 50256,
...
}
```
Those don't seem to have any effect though and when I look the ids up in the vocab, it's this line*:
` "ĠSchÃ¶ffen": 50256, `
This doesn't look like it's really a bos/eos token.

I think one doesn't actually need special tokens much when training gpt2 but they seem to be in the vocab albeit not being used in the tokenizer and there are mentions of it in the model config that are confusing to me. So I was wondering if you could help me make sense of this.

I'm using transformers library 4.2.1

*about the broken umlauts: it's how it's shown to me in any editor or browser even though I was expecting it to be utf-8. But since the model works and produces proper umlauts I'm guessing I'm missing something here

**Comment by stefan-it** [comment]
Hi @wbwseeker ,

thanks for that hint! The `bos_token_id` and `eos_token_id` information is indeed wrong, I will fix that soon on the model hub! I think that information is only used e.g. in the text generation pipeline.

Regarding to the umlauts question: this is no bug, it is just an internal representation of the byte pair encoding. You can see the same behavior e.g. with the German RoBERTa model called "GottBERT". Just an example:

```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("uklfr/gottbert-base")

tokenizer_2.convert_ids_to_tokens([27584])
```

this would output `['ĠMÃ¼nze']` (internal bpe representation). Then the tokenizer would convert it into a "real" string/token representation with:

```
tokenizer.convert_tokens_to_string(["ĠMÃ¼nze"])
```

it correctly outputs ` Münze` then. The GottBERT is chosen, because it uses the same tokenization strategy as used for `german-gpt2` model.

I hope this helps :hugs:

**Comment by stefan-it** [comment]
I fixed the `eos_token_id` and `bos_token_id` in the model config.

Next time when you use the model, you should see:

```bash
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 666/666 [00:00<00:00, 232kB/s]
```

This indicates, that a new model config is downloaded (so that you're not using an old cached version locally).

**Comment by wbwseeker** [comment]
Hey, thanks for the quick answer.

Since you set the ids to 52000 now, should I assume that `<s>, </s>, <pad>, ...` in the vocabulary are not actually used as special tokens?

And thanks for the explanation of the vocab encoding 👍

**Comment by stefan-it** [comment]
Hi @wbwseeker , sorry for the late reply! The `<s>` and so on tokens are well defined in the Transformers implementation (and set by default) so they aren't specified in the configuration file.

**Comment by wbwseeker** [comment]
No worries, thanks for the answer and for the great work 👍
