### ISSUE TITLE
<unk> token encoding and decoding

### ISSUE THREAD

**Issue by tanujjain** [stefan-it/german-gpt2#8]
After initializing the gpt-2 model with:

```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("dbmdz/german-gpt2")
```
I tried to encode a `<unk>` symbol: `tokenizer.encode('<unk>')` and I get a sequence of 3 tokens: `[32, 3043, 34]` which correspond to `'<', 'unk' and  '>' `respectively.

However, when I check  `'<unk>' in tokenizer.get_vocab().keys()`, I get `True` as the output. 

Indeed,  `tokenizer.get_vocab()['<unk>']` returns `3`. So, encoding and decoding an unknown token gives different results, which is inappropriate behaviour IMO.  

Is there a case where `<unk>` will get encoded to a single index of `3` ?

**Comment by stefan-it** [comment]
Hi @tanujjain , 

I think the `<unk>` was automatically added by the tokenizers implementation. As it is a byte-level BPE approach, the unk-token id should never appear in your encoded text :)

**Comment by tanujjain** [comment]
Ok, got it.
